config/routes.rb
HolidayContest::Application.routes.draw do

  get "thank_you" => 'thank_you#index'

  get 'submissions/new'
  post 'submissions' => 'submissions#create'
  match '/submissions' => redirect('/')

  get "home/index"

root :to => 'home#index'

end

app/models/home.rb
class Home
  
  
end

app/models/submission.rb
class Submission
  include MongoMapper::Document

  key :name, String, :required => true
  key :email, String, :required => true, :email => true
  timestamps!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params.has_key?(:signed_request)
      if cookies[:has_submitted].present?
        return redirect_to thank_you_path
      end
      begin
        p = params['signed_request'].split('.')[1]
        json = Base64.decode64(p + "=" * (4 - p.size % 4))
        data = ActiveSupport::JSON.decode(json)
        liked = data["page"]["liked"]
        if liked
          return redirect_to :controller => 'submissions', :action => 'new'
        end
      rescue
        @error = "#{$!}"
      end
    end
    @height = 860
  end

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  # GET /submissions
  # GET /submissions.json
=begin
  def index
    @submissions = Submission.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @submissions }
    end
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
    @submission = Submission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @submission }
    end
  end
=end
  # GET /submissions/new
  # GET /submissions/new.json
  def new
    if cookies[:has_submitted].present?
      return redirect_to thank_you_path
    end

    @height = 1550

    @submission = Submission.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @submission }
    end
  end
=begin
  # GET /submissions/1/edit
  def edit
    @submission = Submission.find(params[:id])
  end
=end
  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(params[:submission])

    respond_to do |format|
      if @submission.save
        cookies[:has_submitted] = true
        format.html { redirect_to thank_you_path, notice: 'Submission was successfully created.' }
        format.json { render json: @submission, status: :created, location: @submission }
      else
        @height = 1800
        format.html { render action: "new" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end
=begin
  # PUT /submissions/1
  # PUT /submissions/1.json
  def update
    @submission = Submission.find(params[:id])

    respond_to do |format|
      if @submission.update_attributes(params[:submission])
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy

    respond_to do |format|
      format.html { redirect_to submissions_url }
      format.json { head :ok }
    end
  end
=end  
end

app/controllers/thank_you_controller.rb
class ThankYouController < ApplicationController
  def index
    @height = 920
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/submission_helper.rb
module SubmissionHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/thank_you_helper.rb
module ThankYouHelper
end

app/views/home/index.html.erb
<% unless @error.blank? %>
 <!-- 
value: <%= params[:signed_request] %>

Error: <%= @error %>
-->
<% end %>
<p class="center medium"><a href="http://on.fb.me/uyT5vD">
  <%= image_tag("like.png") %>
<span>Like us to enter our holiday contest</span>
  <%= image_tag("monkey.png") %></a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DMB Stream Holiday Contest</title>
  <link href='http://fonts.googleapis.com/css?family=Niconne' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta property="fb:app_id" content="257982467594856" />
  <meta property="fb:admins" content="688950931" />
  <meta property="og:image" content="<%= image_path("monkey.png") %>">

  <script type="text/javascript" src="http://connect.facebook.net/en_US/all.js"></script>
  <script>
window.fbAsyncInit = function(){  
    fb.canvas.setautoresize();
  }
  </script>
</head>
<body onload="FB.Canvas.setSize({width: 520, height: <%= @height %>})">
<div id="fb-root"></div>
<script type="text/javascript" charset="utf-8">
    FB.Canvas.setSize();
</script>
<h1 class="reduced center">Happy Holidays</h1>

<%= yield %>

  <footer>
    <p class="disclaimer1">
      Winners will be announced on or after December 25, 2011.  
      This contest is not affiliated with Facebook. You must like DMBStream on Facebook to view 
      the contest entry form.
    </p>
    <p class="disclaimer2">Tree image by <a href="http://minercia.deviantart.com/" class="link" target="_parent">minercia</a></p>
  </footer>
</body>
</html>

app/views/submissions/_form.html.erb
<div class="center">
  <%= image_tag("prizes.png") %>
  <p class="medium">
  	1st - All 3 2011 Gorge posters<br />
    2nd - $75 DMB store gift card<br />
	3rd - $25 DMB store gift card
  </p>
</div>
<%= form_for(@submission) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="medium formfields">
    <div class="field medium">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field medium">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
  </div>
  <div class="actions center">
    <%= f.submit "Submit Entry", :class => "btn" %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<h2>Listing submissions</h2>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @submissions.each do |submission| %>
  <tr>
    <td><%= submission.name %></td>
    <td><%= submission.email %></td>
    <td><%= link_to 'Show', submission %></td>
    <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
    <td><%= link_to 'Destroy', submission, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Submission', new_submission_path %>

app/views/submissions/new.html.erb
<p class="reduced center large">Enter to win</p>

<%= render 'form' %>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @submission.name %>
</p>

<p>
  <b>Email:</b>
  <%= @submission.email %>
</p>


<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>

app/views/thank_you/index.html.erb
<h2 class="center">Thank You</h2>
<p class="center">Thank you for your submission! Please check out our <a href="http://twitter.com/dmbstream" class="link" target="_parent">twitter stream</a> as well!</p>